name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build with Maven
      env:
        NODE_OPTIONS: "--openssl-legacy-provider"
      run: mvn -B package --file pom.xml
    - name: Build and publish Docker image
      uses: ilteoood/docker_buildx@1.1.0
      with:
        tag: latest
        imageName: drasyl/drasyl-network-explorer
        platform: linux/amd64
        publish: true
        dockerUser: ${{ secrets.DOCKER_HUB_USER }}
        dockerPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}